; int isalnum (int c)
.global isalnum
; int isalpha (int c)
.global isalpha
; int iscntrl (int c)
.global iscntrl
; int isdigit (int c)
.global isdigit
; int isgraph (int c)
.global isgraph
; int islower (int c)
.global islower
; int isprint (int c)
.global isprint
; int ispunct (int c)
.global ispunct
; int isspace (int c)
.global isspace
; int isupper (int c)
.global isupper
; int isxdigit (int c)
.global isxdigit
; int tolower (int c)
.global tolower
; int toupper (int c)
.global toupper
